# Configuration file

# Camel
camel:
  context:
    name: threescale-camel-service

# Camel Proxy service
camel-proxy-service:
  port:
    nonsecure: 9090
    secure: 9443
  keystore:
    mount-path: ./tls-keys
    passphrase: P@ssw0rd

# Quarkus
quarkus:
  # Display the banner
  banner:
    enabled: true
  # Eventually, the client should trust a self signed certificate presented by the API server
  kubernetes-client:
    trust-certs: true
  # Enable native SSL support
  ssl:
    native: true

  # The container registry to use
  container-image:
    registry: image-registry.openshift-image-registry.svc:5000

  ## Quarkus OpenShift extension configuration
  openshift:
    # The kind of the deployment resource to use. Supported values are 'Deployment', 'StatefulSet', 'Job', 'CronJob' and 'DeploymentConfig' defaulting to the latter.
    deployment-kind: Deployment
    # Part of the `Threescale-Extensions` Application Group
    part-of: Threescale-Extensions
    # Apache Camel icon
    labels:
      app.openshift.io/runtime: camel
    # The build config strategy to use
    build-strategy: DOCKER
    # The default Dockerfile to use for jvm builds
    jvm-dockerfile: src/main/docker/Dockerfile.jvm
    # The default Dockerfile to use for native builds
    native-dockerfile: src/main/docker/Dockerfile.native
    ports:
      # Allows the proxy ports to be included in the generated resources (DeploymentConfig and Service)
      proxy:
        container-port: ${camel-proxy-service.port.nonsecure}
      proxy-secure:
        container-port: ${camel-proxy-service.port.secure}
      # Requirement of "hawtio-enabled" deployments. A container needs to have a port named "jolokia"
      jolokia:
        container-port: ${jolokia.port}
    # Enable the jolokia java-agent on the quarkus application
    env:
      vars:
        JAVA_OPTS_APPEND: -javaagent:lib/main/org.jolokia.jolokia-agent-jvm-${jolokia.version}-javaagent.jar=protocol=${jolokia.protocol},host=${jolokia.host},port=${jolokia.port},useSslClientAuthentication=${jolokia.useSslClientAuthentication},caCert=${jolokia.caCert},clientPrincipal.1=${jolokia.clientPrincipal.1},extendedClientCheck=${jolokia.extendedClientCheck},discoveryEnabled=${jolokia.discoveryEnabled}
    # The number of desired pods
    replicas: 1
    # Expose OpenShift route
    route:
      expose: false
    # CPU and Memory resources requirements when deployed on Kubernetes/OpenShift
    resources:
        requests:
            cpu: 30m
            memory: 512Mi
        limits:
            cpu: 500m
            memory: 512Mi
    # The type of service that will be generated for the application
    service-type: ClusterIP
    # Secret to mount and where to mount it
    secret-volumes:
      keystore-volume:
        secret-name: threescale-camel-service-keystore-secret
    mounts:
      keystore-volume:
        path: /mnt

  # OpenTelemetry configuration. This is leveraged by Camel Quarkus OpenTelemetry extension
  ## Identifier for the origin of spans created by the application
  application:
    name: ${camel.context.name}
  otel:
    exporter:
      otlp:
        traces:
          endpoint: http://localhost:4317

  # OIDC client
  oidc-client:
    # The base URL of the OpenID Connect (OIDC) server
    auth-server-url: https://sso.apps.ocp4.jnyilimb.eu/realms/demo
    # The client-id of the application. Each application has a client-id that is used to identify the application
    client-id: threescale-camel-service
    # Client secret which is used for a `client_secret_basic` authentication method.
    credentials:
      secret: vebmUALy0SuPhTsj5v0aJFyuafIbjhnx
  
  ## Quarkus native build 
  native:
    # If all character sets should be added to the native image. This increases image size
    add-all-charsets: true
    # If this build should be done using a container runtime. 
    # If this is set docker will be used by default, unless container-runtime is also set.
    container-build: true

  ## Camel Quarkus
  camel:
    # Microprofile Camel Health checks
    # Cf. https://camel.apache.org/camel-quarkus/latest/extensions/microprofile-health.html
    health:
      enabled: true

    # Micrometer Camel Metrics
    # Cf. https://camel.apache.org/camel-quarkus/3.15.x/reference/extensions/micrometer.html
    metrics:
      enable-route-policy: true
      enable-message-history: true
      enable-exchange-event-notifier: true
      enable-route-event-notifier: true
      enable-instrumented-thread-pool-factory: true

    # native mode configuration
    native:
      # A comma separated list of Ant-path style patterns to match class names
      # that should be registered for reflection.
      # Reference: https://camel.apache.org/camel-quarkus/latest/user-guide/native-mode.html#reflection
      reflection:
        include-patterns: java.lang.Exception,java.lang.IllegalArgumentException,io.quarkus.oidc.client.OidcClientException

  # Quarkus log
  log:
    category:
      io.quarkus.oidc:
        min-level: DEBUG
        level: DEBUG

# Only when running in prod profile
"%prod":
  quarkus:
    # Quarkus kubernetes config extension
    kubernetes-config:
      # Enable to look up the configuration from the API server
      enabled: true
      # ConfigMaps (list of strings) to look for in the namespace that the Kubernetes Client has been configured for
      config-maps: threescale-camel-service-config
      secrets:
        # Secrets (list of strings) to look for in the namespace that the Kubernetes Client has been configured for 
        ~: threescale-camel-service-secret
        # Enable to generate the necessary role and corresponding role binding
        enabled: true